# Generated by Django 5.0.6 on 2024-10-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CardScanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CardScanning.card')),
            ],
        ),
    ]
