# Generated by Django 5.0.6 on 2024-10-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CardScanning', '0001_initial'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/qr_codes/')),
                ('associated_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CardScanning.card')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManagement.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QrCodesManagement.qrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.customuser')),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
