# Generated by Django 5.0.6 on 2024-10-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QrCodesManagement', '0001_initial'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManagement.customuser'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QrCodesManagement.qrcode'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.customuser'),
        ),
    ]
