# Generated by Django 5.1.2 on 2024-10-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodesManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
